### ISSUE TITLE
Use lapx insted of lap

### ISSUE THREAD

**Issue by johnnynunez** [gitmehrdad/SFSORT#2]
better and updated code: https://github.com/rathaROG/lapx

**Comment by gitmehrdad** [comment]
Thank you for your suggestion. Your work intrigues me, particularly because I've encountered difficulties running the lap on Windows! I have a few questions:

1- How much faster is your method compared to previous approaches? Does it leverage parallel processing or SIMD techniques to optimize speed?

2- Have you assessed the accuracy of your method? There have been reports of bugs in prior implementations of the algorithm, including the one in Scipy.

**Comment by johnnynunez** [comment]
> Thank you for your suggestion. Your work intrigues me, particularly because I've encountered difficulties running the lap on Windows! I have a few questions:
> 
> 1- How much faster is your method compared to previous approaches? Does it leverage parallel processing or SIMD techniques to optimize speed?
> 
> 2- Have you assessed the accuracy of your method? There have been reports of bugs in prior implementations of the algorithm, including the one in Scipy.

lapx is really lap, but it was discontinued by the creators. Now it is maintained by the community and used by the standard libraries. And it is compatible with the most recent versions of Python.

**Comment by gitmehrdad** [comment]
OK. Thank you.
