### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by akirs82** [gitmehrdad/SFSORT#5]
Hello Mehrdad Morsali,

Great work ,probably the first tracker which adapts to the detection models capabilities . I have one doubt though, what is the CPU load that you are getting in these benchmarks u have provided?

regards
akirs

**Comment by gitmehrdad** [comment]
Dear Akirs,

Thank you for your comment.

The main purpose of our work is to diminish the computational load as much as possible. While the CPU architecture itself affects the reported CPU load, I've observed an average CPU usage of 1.4% and an average RAM usage of 300KB when running the tracker on a Core i7-8700 processing the video sequence named MOT17-04 in the MOT17 benchmark. Since this video sequence is the most crowded one in the dataset, it is expected that running the algorithm on other videos will consume fewer computational resources.

You can also run the available Jupyter Notebook on Google Colab and personally confirm the minimal computational load of our tracking algorithm. Our proposed system consists of an object detector and a tracking algorithm. While different object detectors with varying computational loads and capabilities may limit their application on any platform, we assure you that, based on experiments, you can run the tracking algorithm on any device, ranging from simple edge processors (e.g., microcontrollers) to complex cloud processing arrays.

Best regards,
Mehrdad
