### ISSUE TITLE
calculate_cost

### ISSUE THREAD

**Issue by a228949** [gitmehrdad/SFSORT#6]
Hi! The definition of bounding box width and height seems to be reversed in the `calculate_cost` function. This definition matches what is presented in your paper but does not align with the results from YOLO.

**Comment by gitmehrdad** [comment]
Hi,

Thank you for your comment. The difference in definitions arises because the Computer Vision community defines the x-axis and y-axis differently than the Mathematics community. Therefore, we decided to adhere to the Computer Vision terminology in our work. Nevertheless, the tracker's output is correct as it accurately visualizes the bounding boxes. So, you can use it without any concerns.
